version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usuarios_db
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  flask_api_productos:
    build: ./productos/flaskapi
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=productos_db
    ports:
      - "5001:5001"

  nodeview_productos:
    build: ./productos/nodeview
    depends_on:
      - flask_api_productos
    environment:
      - API_URL=http://flask_api_productos:5001/api/productos
    ports:
      - "3001:3001"

  flask_api_usuarios:
    build: ./usuarios/flaskapi
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=usuarios_db
    ports:
      - "5002:5002"

  nodeview_usuarios:
    build: ./usuarios/nodeview
    depends_on:
      - flask_api_usuarios
    environment:
      - API_URL=http://flask_api_usuarios:5002/api/usuarios
    ports:
      - "3002:3002"

  flask_api_pedidos:
    build: ./pedidos/flaskapi
    depends_on:
      - rabbitmq
      - mysql
      - flask_api_productos
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=pedidos_db
      - API_URL=http://flask_api_pedidos:5003/api/pedidos
      - API_USUARIOS=http://flask_api_usuarios:5002/api/usuarios
      - API_PRODUCTOS=http://flask_api_productos:5001/api/productos
    ports:
      - "5003:5003"

  nodeview_pedidos:
    build: ./pedidos/nodeview
    depends_on:
      - flask_api_pedidos
    environment:
      - API_URL=http://flask_api_pedidos:5003/api/pedidos
    ports:
      - "3003:3003"
  
  login_flaskapi:
    build: ./login/flaskapi
    depends_on:
      - rabbitmq
      - flask_api_usuarios
    environment:
      - RABBITMQ_HOST=rabbitmq
      - API_USUARIOS=http://flask_api_usuarios:5002/api/usuarios
    ports:
      - "5005:5005"

  login_nodeview:
    build: ./login/nodeview
    depends_on:
      - login_flaskapi
    environment:
      - API_LOGIN=http://login_flaskapi:5005/api/login
    ports:
      - "3005:3005"
  mensajeria_flaskapi:
    build: ./mensajeria/flaskapi
    ports:
      - "5006:5006"

volumes:
  mysql_data:

